name: Node.js Build and Artifact Upload

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js 18
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'  # Caches `node_modules` automatically

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Pre-build phase
      - name: Pre-build step
        run: echo "Installing source NPM dependencies..."

      # Build phase (optional)
      - name: Build project
        run: |
          echo "Build started on $(date)"
          if npm run build; then
            echo "Build completed successfully"
          else
            echo "No build script found, skipping build"
          fi
          npm prune --production

      # Post-build phase
      - name: Post-build step
        run: echo "Post-build steps completed on $(date)"

      # Upload artifacts (optional, if you want to store the build output)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-output
          path: |
            ./dist/**      # Change 'dist' to your actual output directory
            !**/*:*        # Exclude files with invalid characters
